### ISSUE TITLE
Can I get a cross Icon on right side of each applied tag?

### ISSUE THREAD

**Issue by JerryGoyal** [bseth99/jquery-ui-multisearch#3]
How can I get a cross Icon on right side of each applied tag so that I can remove those tags by clicking on the cross icon.
Thanks.

**Comment by bseth99** [comment]
The design allows you to implement any html for the tag and can understand an element with an attribute `data-action="remove"`.  Just override `formatSelectedItem` which, by default, returns the following HTML:

````
formatSelectedItem: function( data ) {
   return '<a href="#">'+data.name+'</a>';
},
````

return some HTML that includes a link with that attribute:

````
<a href="#" data-action="remove">x</a>
````

**Comment by JerryGoyal** [comment]
Thanks a lot @bseth99 it works!

**Comment by JerryGoyal** [comment]
hi @bseth99 could you also tell me how can I show dropdown menu of all tags when I focus on input textbox.
Right now I've to enter atleast 1 char to show dropdown menu.

I looked in your code but couldn't find the proper way to enable this feature.
